version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  build:  # Choose any name, such as `build`
      # The primary container, where your job's commands will run
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout # check out the code in the project directory
        - run: echo "hello world" # run the `echo` command


#  create_infrastructure: 
#    docker:
#      - image: amazon/aws-cli
#    steps:
 #     - checkout
  #    - run:
   #       name: Create Cloudformation Stack
    #      command: |
     #       aws cloudformation deploy \
      #        --template-file template.yml \
       #       --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
        #      --region us-west-2

  configure_infrastructure: 
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["bf:28:46:dd:05:23:e0:98:e4:b7:b1:b3:f0:4f:48:fe"] # You can get this ID in the section where you registered the SSH Key
      - run:
          name: Install Ansible
          command: |
            # install the dependencies needed for your playbook
            apk update
            apk add --update ansible 
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory main.yml
# Sequential workflow
workflows:
  # Name the workflow
  prod2Workflow:
    jobs:
      - build
      #- create_infrastructure
      - configure_infrastructure